### ISSUE TITLE
System Parameter File needs to be updated with results after running Thermal Network

### ISSUE THREAD

**Issue by tanushree04** [NREL/ThermalNetwork#5]
The thermalnetwork cli call used to size GHE, takes the system parameter file path as an input. This file needs to be updated in the same path with the following fields : 

- the number of boreholes
- size of boreholes

**Comment by vtnate** [comment]
@tanushree04 Can you provide some more detail? For instance, if we want data from the SimulationSummary.json, which fields are important to return to the sys-param file? I see `number_of_boreholes` in that file. For the size of the boreholes, should we have `active_borehole_length`, `borehole_diameter`, `borehole_buried_depth`? Do we also need `borehole_spacing`? Do any other fields get modified by ThermalNetwork?

**Comment by tanushree04** [comment]
@vtnate https://github.com/NREL/ThermalNetwork/blob/main/demos/sdk_output_skeleton_2_ghe_sequential/run/baseline_scenario/ghe_dir/sys_params.json#L156-L157

These 2 fields need to be updated
